import { UIConf } from "../../base/ui/UIManager";

export enum UIID {
    UILogin,
    UIMain,
    UITips,
    UIAlertView,
    UICreateRole,
    UICloth,
    UISearch,
    UIConfirm,
    UIClothStore,
    UIClothArmoire,
    UIClothDecompose,
    UIClothBuy,
    UIDropItem,
    UIChapter,
    UIPlot,
    UIMemory,
    UIWorkshop,
    UIWorkshopBag,
    UIWorkshopDesc,
    UIWorkshopUpgrade,
    UIOrder,
    UIOrderDesc,
    UIClothScoreTips,
    UIClothDetails,
    UIClothScoreResult,
    UIClothScoreDetails,
    UIAccess,
    UIRetinue,
    UIRetinueBreak,
    UIRetinueFormation,
    UIRetinueInfo,
    UIRetinueList,
    UIRetinueStar,
    UIRetinueSuperSkill,
    UIRetinueUpgrade,
    UIItemCount,
    UIItemDetails,
    UIItemExplore,
    UIItemExploreResult,
    UIItemUse,
    UIItemSell,
    UIBattle,
    UIBattlePos,
    UIBattleResult,
    UIItemInfoView,
    UIBagView,
    UIBagVIPView,
    UIBuyCardView,
    UIBuyCardTenView,
    UIRetinuePreview,

}


export enum UILEVEL {
    BottomUI = 0,
    CommonUI = 1,
    TopUI = 2,
}

export let UIConfig: { [key: number]: UIConf } = {
    [UIID.UILogin]: { prefab: "prefabs/ui/UILogin", preventTouch: false },
    [UIID.UIMain]: { prefab: "prefabs/ui/UIMain", preventTouch: false },
    [UIID.UITips]: { prefab: "prefabs/ui/UITips", preventTouch: false },
    [UIID.UIAlertView]: { prefab: "prefabs/ui/UIAlertView", preventTouch: false },
    [UIID.UICreateRole]: { prefab: "prefabs/ui/UICreateRole", preventTouch: false },
    [UIID.UICloth]: { prefab: "prefabs/ui/UICloth", preventTouch: false },
    [UIID.UISearch]: { prefab: "prefabs/ui/UISearch", preventTouch: false },
    [UIID.UIConfirm]: { prefab: "prefabs/ui/UIConfirm", preventTouch: false },
    [UIID.UIClothArmoire]: { prefab: "prefabs/ui/UIClothArmoire", preventTouch: false },
    [UIID.UIClothDecompose]: { prefab: "prefabs/ui/UIClothDecompose", preventTouch: false },
    [UIID.UIClothStore]: { prefab: "prefabs/ui/UIClothStore", preventTouch: false },
    [UIID.UIClothBuy]: { prefab: "prefabs/ui/UIClothBuy", preventTouch: false },
    [UIID.UIDropItem]: { prefab: "prefabs/ui/UIDropItem", preventTouch: false },
    [UIID.UIChapter]: { prefab: "prefabs/ui/UIChapter", preventTouch: false },
    [UIID.UIPlot]: { prefab: "prefabs/ui/UIPlot", preventTouch: false },
    [UIID.UIMemory]: { prefab: "prefabs/ui/UIMemory", preventTouch: false },
    [UIID.UIWorkshop]: { prefab: "prefabs/ui/UIWorkshop", preventTouch: false },
    [UIID.UIWorkshopBag]: { prefab: "prefabs/ui/UIWorkshopBag", preventTouch: false },
    [UIID.UIWorkshopDesc]: { prefab: "prefabs/ui/UIWorkshopDesc", preventTouch: false },
    [UIID.UIWorkshopUpgrade]: { prefab: "prefabs/ui/UIWorkshopUpgrade", preventTouch: false },
    [UIID.UIOrder]: { prefab: "prefabs/ui/UIOrder", preventTouch: false },
    [UIID.UIOrderDesc]: { prefab: "prefabs/ui/UIOrderDesc", preventTouch: false },
    [UIID.UIClothScoreTips]: { prefab: "prefabs/ui/UIClothScoreTips", preventTouch: false },
    [UIID.UIClothDetails]: { prefab: "prefabs/ui/UIClothDetails", preventTouch: false },
    [UIID.UIClothScoreResult]: { prefab: "prefabs/ui/UIClothScoreResult", preventTouch: false },
    [UIID.UIClothScoreDetails]: { prefab: "prefabs/ui/UIClothScoreDetails", preventTouch: false },
    [UIID.UIAccess]: { prefab: "prefabs/ui/UIAccess", preventTouch: false },
    [UIID.UIRetinue]: { prefab: "prefabs/ui/UIRetinue", preventTouch: false },
    [UIID.UIRetinueBreak]: { prefab: "prefabs/ui/UIRetinueUpgrade", preventTouch: false },
    [UIID.UIRetinueFormation]: { prefab: "prefabs/ui/UIRetinueFormation", preventTouch: false },
    [UIID.UIRetinueInfo]: { prefab: "prefabs/ui/UIRetinueInfo", preventTouch: false },
    [UIID.UIRetinueList]: { prefab: "prefabs/ui/UIRetinueList", preventTouch: false },
    [UIID.UIRetinueStar]: { prefab: "prefabs/ui/UIRetinueUpgrade", preventTouch: false },
    [UIID.UIRetinueSuperSkill]: { prefab: "prefabs/ui/UIRetinueSuperSkill", preventTouch: false },
    [UIID.UIRetinueUpgrade]: { prefab: "prefabs/ui/UIRetinueUpgrade", preventTouch: false },
    [UIID.UIItemCount]: { prefab: "prefabs/ui/UIItemCount", preventTouch: false },
    [UIID.UIItemDetails]: { prefab: "prefabs/ui/UIItemDetails", preventTouch: false },
    [UIID.UIItemExplore]: { prefab: "prefabs/ui/UIItemExplore", preventTouch: false },
    [UIID.UIItemExploreResult]: { prefab: "prefabs/ui/UIItemExploreResult", preventTouch: false },
    [UIID.UIBattle]: { prefab: "prefabs/ui/UIBattle", preventTouch: false },
    [UIID.UIBattlePos]: { prefab: "prefabs/ui/UIBattlePos", preventTouch: false },
    [UIID.UIBattleResult]: { prefab: "prefabs/ui/UIBattleResult", preventTouch: false },
    [UIID.UIItemInfoView]: { prefab: "prefabs/ui/ItemInfo", preventTouch: false },
    [UIID.UIItemUse]: { prefab: "prefabs/ui/ItemUse", preventTouch: false },
    [UIID.UIItemSell]: { prefab: "prefabs/ui/ItemSell", preventTouch: false },
    [UIID.UIBagView]: { prefab: "prefabs/ui/UIBag", preventTouch: false },
    [UIID.UIBagVIPView]: { prefab: "prefabs/ui/UIBagVIP", preventTouch: false },
    [UIID.UIBuyCardView]: { prefab: "prefabs/ui/UIBuyCard", preventTouch: false },
    [UIID.UIBuyCardTenView]: { prefab: "prefabs/ui/UIBuyCardTen", preventTouch: false },
    [UIID.UIRetinuePreview]: { prefab: "prefabs/ui/UIRetinuePreview", preventTouch: false },
}